# DBMS Settings
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/toy1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0639
    
    
# logging
logging:
  level:
    com.toy1.web.config.auth : TRACE